title: "teleoperator.app"
description: "surveillance manager & integrator with helpdesk on one mobile app"
mermaid:
  src: "mermaid.js"
plugins:
  - "jekyll-github-metadata"
  - "jekyll-readme-index"
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false
