version: '3'

services:

  build:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - build

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
