version: '3.8'
services:
  app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=exampleuser
      - POSTGRES_PASSWORD=examplepass
      - POSTGRES_DB=exampledb
    ports:
      - "5432:5432"
